image: "giraf/xamarin-android:latest"

stages:
    - "build"
    - "test"
    - "deploy"

build_android:
    stage: "build"
    script:
        - cp $CI_PROJECT_DIR/WeekPlanner/appsettings.template.json $CI_PROJECT_DIR/WeekPlanner/appsettings.Development.json
        - mono /nuget.exe restore $CI_PROJECT_DIR
        - msbuild /t:PackageForAndroid /p:Configuration=Release /p:AndroidLinkMode=None $CI_PROJECT_DIR/Droid/WeekPlanner.Droid.csproj
        # Missing: iOS Version
        # Missing: Windows Version

        - mv $CI_PROJECT_DIR/Droid/obj/Release/android/bin/dk.aau.cs.giraf.weekplanner.apk $CI_PROJECT_DIR/dk.aau.cs.giraf.weekplanner.apk

    artifacts:
        paths:
            - $CI_PROJECT_DIR/dk.aau.cs.giraf.weekplanner.apk
        expire_in: 20 min

test:
    stage: "test"
    script:
        - cp $CI_PROJECT_DIR/WeekPlanner/appsettings.template.json $CI_PROJECT_DIR/WeekPlanner/appsettings.Development.json
        - find / mstest.exe
        - mono /nuget.exe restore $CI_PROJECT_DIR
        - find / mstest.exe
        - msbuild $CI_PROJECT_DIR/WeekPlanner.Tests/WeekPlanner.Tests.csproj
        - find / mstest.exe
        - mstest $CI_PROJECT_DIR/WeekPlanner.Tests/WeekPlanner.Tests.csproj

deploy:
    stage: "deploy"
    when: always
    only: 
        - master
        - release
    dependencies:
        - build_android
    script:
        # Turns the secret keystore environment variable into its normal keystore form, now ready for signing
        - echo $KEYSTORE | base64 -di > $CI_PROJECT_DIR/giraf.keystore
        - /android/build-tools/27.0.3/zipalign -f -v 4 $CI_PROJECT_DIR/dk.aau.cs.giraf.weekplanner.apk $CI_PROJECT_DIR/dk.aau.cs.giraf.weekplanner-Signed.apk
        - /android/build-tools/27.0.3/apksigner sign --ks $CI_PROJECT_DIR/giraf.keystore --ks-key-alias $KEYSTOREALIAS --ks-pass pass:$KEYSTOREPASSWORD ./dk.aau.cs.giraf.weekplanner-Signed.apk

        - /android/build-tools/27.0.3/apksigner verify -v $CI_PROJECT_DIR/dk.aau.cs.giraf.weekplanner-Signed.apk
        # Verifying is not necessary for deployment
    artifacts:
        paths:
            - $CI_PROJECT_DIR/dk.aau.cs.giraf.weekplanner-Signed.apk
        expire_in: 1 week
