codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
        
comment:
  layout: "diff,flags,files"
  behavior: default
  require_changes: yes

ignore:
  - ".github/**/*"
  - "./*"
