name: Flutter Android and iOS verification

on: [push]

env:
  flutter_channel: "stable"
  flutter_version: "3.13.7"
  java_version: "12.x"

jobs:
  Android:
    name: Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
          - os: windows-latest
            flutter_path: '%USERPROFILE%\hostedtoolcache\flutter'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
      - run: flutter pub get
        name: Get dependencies

      - run: flutter doctor
        name: Doctor

      - run: flutter analyze
        name: Linter
      - run: flutter test --coverage
        name: Tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  iOS:
    name: iOS on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
      - name: Set XCode 15.0.1
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
          xcodebuild -version
      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPSTORE_P12_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_P12_PASSWORD }}
      - uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: dk.girafsvenner.weekplanner
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      - run: flutter pub get
        name: Get dependencies
      - run: flutter analyze
        name: Linter
      - run: flutter test
        name: Tests
