name: Flutter verification

on: [push]

env:
  flutter_channel: 'stable'
  flutter_version: '2.0.5'
  java_version: '12.x'

jobs:
  Android:
    name: Flutter on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
          - os: windows-latest
            flutter_path: '%USERPROFILE%\hostedtoolcache\flutter'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
          path: ${{ matrix.flutter_path }}
      - run: flutter pub get
        name: Get dependencies

      - run: flutter doctor
        name: Doctor

      - run: flutter test --coverage
        name: Tests
