name: GIRAF

on: [push]

env:
  flutter_channel: "stable"
  flutter_version: "3.24.1"
  java_version: "17.0.8+101"

jobs:
  Android:
    name: Flutter on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
          - os: windows-latest
            flutter_path: '%USERPROFILE%\hostedtoolcache\flutter'

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cp .env.example .env
        shell: bash

      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.java_version }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}

      - run: flutter pub get
        name: Get dependencies

      - run: flutter doctor
        name: Doctor

      - run: flutter analyze
        name: Linter

      - run: flutter test test/blocs test/exceptions test/models --coverage
        name: Tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
