name: CI

on: [push]

jobs:
  build-and-test-android:
    name: Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.x"
          channel: 'stable'
      - run: flutter pub get
        name: Get dependencies

      - run: flutter doctor
        name: Doctor

      - run: flutter analyze
        name: Linter
      - run: flutter test
        name: Tests
      - run: flutter build apk
        name: Build APK
      - name: Upload Artifact 
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Giraf Weekplanner
          path: build/app/outputs/apk/release/app-release.apk
          
  deploy-to-playstore:
    needs: build-and-test-android
    name: Android on Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: Giraf Weekplanner
          # Destination path
          path: build/apk/weekplanner.apk
      - name: Publish
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: dk.aau.cs.giraf.weekplanner
          releaseFile: build/apk/weekplanner.apk
  
  build-and-test-ios:
    name: iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.x"
          channel: 'stable'
      - run: flutter pub get
        name: Get dependencies
      - run: flutter analyze
        name: Linter
      - run: flutter test
        name: Tests
      - run: flutter build ios --release --no-codesign
        name: Build for iOS
