# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment_checklist:
    runs-on: [ubuntu-latest]
    steps:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Please use the following checklist. Feel free to check it off as you go along.

          **Code Design**
          - [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
          - [ ] Could this code, to the best of your knowledge, have reused existing code?
          - [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
          - [ ] Does it introduce functionality that is not necessary for solving the problem?

          **Code Readability and Maintainability**
          - [ ] Are names meaningful and self-documenting?
          - [ ] Is it understandable, by reading the code, what it does?
          - [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
          - [ ] Is it understandable, by reading the tests, what they do?
          - [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
          - [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
          - [ ] Are error messages in the code understandable?
          - [ ] Are confusing sections of code covered by comments?

          **Functionality**
          For this part, open the app, and test:
          - [ ] Are the features that the code claims to implement, actually implemented?
          - [ ] Does it look like the code has bugs?
          - [ ] Are all new screens reachable through in-app navigation?

          **Points for Discussion and Reflection**
          - [ ] Are UI messages, that the user might meet, actually helpful?
          - [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
          - [ ] Is there well written code in this? Remember to tell the developer!
